Repository ITU-BDSA2024-GROUP30/Chirp, pull requests merged in 2024-10, with the labels that each got.

#51 Razor template added and code removed.
  .editorconfig
  .vscode/settings.json
  CheepService.cs
  Chirp.csproj
  Chirp30API/Cheep.cs
  Chirp30API/Chirp30API.csproj
  Chirp30API/Program.cs
  Pages/Public.cshtml
  Pages/Public.cshtml.cs
  Pages/Shared/_Layout.cshtml
  Pages/UserTimeline.cshtml
  Pages/UserTimeline.cshtml.cs
  Program.cs
  Properties/launchSettings.json
  appsettings.Development.json
  appsettings.json
  src/.editorconfig
  src/Chirp.CLI.Client/Chirp.CLI.csproj
  src/Chirp.CLI.Client/Program.cs
  src/Chirp.CLI.Client/UserInterface.cs
  src/SimpleDB/CSVDatabase.cs
  src/SimpleDB/IDatabaseRepository.cs
  src/SimpleDB/SimpleDB.csproj
  src/data/chirp_cli_db.csv
  wwwroot/css/style.css
  wwwroot/favicon/favicon.ico
  wwwroot/images/icon1.png
Labels: enhancement

#52 Minor solution fixes Co-authored-by: Maria arnv@itu.dk
  Chirp.CLI.generated.sln
  test/Chirp.CLI.Client.Tests/UnitTests.cs
  test/Chirp.SimpleDB.Tests/UnitTests.cs
Labels: enhancement

#53 Main build file name fix to work with Azure
  .github/workflows/main_bdsagroup30chirpremotedb.yml
Labels: enhancement

#55 Revert "Removed with: package . from main workflow file"
  .github/workflows/main_bdsagroup30chirpremotedb.yml
Labels: minor fix

#56 Configurations for azure
  .azure/config
Labels: enhancement

#58 To start webapp
  .azure/config
Labels: enhancement, minor fix

#61 Workflow for executable deleted
  .github/workflows/build_and_test.yaml
Labels: restructuring

#62 Sqlite and databases finally working
  CheepService.cs
  Chirp.csproj
  DBFacade.cs
  Pages/Public.cshtml.cs
  Pages/UserTimeline.cshtml.cs
  data/chirp.db
  data/dump.sql
  data/schema.sql
Labels: enhancement

#76 Create LICENSE.md
  LICENSE.md
Labels: documentation
