Repository ITU-BDSA2024-GROUP30/Chirp, pull requests merged in 2024-11, with the labels that each got.

#93 Onion architecture implemented and EF Core foundation added
  Chirp.CLI.generated.sln
  Chirp.csproj
  DBFacade.cs
  Program.cs
  appsettings.json
  data/chirp.db
  src/Chirp.Core/Author.cs
  src/Chirp.Core/Cheep.cs
  src/Chirp.csproj
  src/Database/DBFacade.cs
  src/EFCore/ChirpDBContext.cs
  src/EFCore/Domain Model/Message.cs
  src/EFCore/Domain Model/User.cs
  src/Identity/IdentityUser.cs
  src/Makefile
  src/Migrations/20241023115041_InitialDBSchema.Designer.cs
  src/Migrations/20241023115041_InitialDBSchema.cs
  src/Migrations/ChirpDBContextModelSnapshot.cs
  src/Program.cs
  src/UserFacade/.azure/config
  src/UserFacade/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/UserFacade/Chirp.Infrastructure/Chirp.Services/CheepService.cs
  src/UserFacade/Pages/Public.cshtml
  src/UserFacade/Pages/Public.cshtml.cs
  src/UserFacade/Pages/Shared/_Layout.cshtml
  src/UserFacade/Pages/UserTimeline.cshtml
  src/UserFacade/Pages/UserTimeline.cshtml.cs
  src/UserFacade/Properties/launchSettings.json
  src/UserFacade/wwwroot/css/style.css
  src/UserFacade/wwwroot/favicon/favicon.ico
  src/UserFacade/wwwroot/images/icon1.png
  src/appsettings.Development.json
  src/appsettings.json
  src/data/DbInitializer.cs
  src/data/chirp.db
  src/data/dump.sql
  src/data/schema.sql
  test/Chirp.CLI.Client.Tests/Chirp.CLI.Client.Tests.csproj
  test/Chirp.SimpleDB.Tests/UnitTests.cs
Labels: enhancement, restructuring

#95 Implementation of Navigation Bar UI
  src/Chirp.csproj
  src/Identity/IdentityUser.cs
  src/Program.cs
  src/UserFacade/Pages/Public.cshtml
  src/UserFacade/Pages/Shared/_Layout.cshtml
Labels: enhancement

#100 Create build-and-test-dotnet.yml
  .github/workflows/build-and-test-dotnet.yml
Labels: enhancement, minor fix

#104 Feat: Previous and Next buttons work.
  src/ChirpInfrastructure/CheepRepository.cs
  src/ChirpInfrastructure/CheepService.cs
  src/ChirpWeb/Pages/Public.cshtml
  src/ChirpWeb/Pages/Public.cshtml.cs
  src/ChirpWeb/Pages/UserTimeline.cshtml
  src/ChirpWeb/Pages/UserTimeline.cshtml.cs
Labels: enhancement

#105 Re-Added Navigationbar
  src/ChirpWeb/Pages/Shared/_Layout.cshtml
Labels: restructuring

#106 Test implementation
  .github/workflows/build-and-test-dotnet.yml
  BDSA-24-GR-30-Chirp.sln
  src/ChirpCore/DTOs/CheepDTO.cs
  src/ChirpCore/Domain/Cheep.cs
  test/Chirp.CLI.Client.Tests/UnitTests.cs
  test/Chirp.ChirpCore.Tests/Chirp.ChirpCore.Tests.csproj
  test/Chirp.ChirpCore.Tests/Chirp.ChirpCore.Tests.sln
  test/Chirp.ChirpCore.Tests/UnitTests.cs
  test/Chirp.ChirpInfrastructure.Tests/Chirp.ChirpInfrastructure.Tests.csproj
  test/Chirp.ChirpInfrastructure.Tests/Chirp.ChirpInfrastructure.Tests.sln
  test/Chirp.ChirpInfrastructure.Tests/UnitTests.cs
  test/Chirp.ChirpWeb.Tests/Chirp.ChirpWeb.Tests.csproj
  test/Chirp.ChirpWeb.Tests/Chirp.ChirpWeb.Tests.sln
  test/Chirp.CrossTests/Chirp.CrossTests.csproj
  test/Chirp.CrossTests/Chirp.CrossTests.sln
  test/Chirp.SimpleDB.Tests/UnitTests.cs
Labels: restructuring, testing

#112 Changed ordering of Cheeps, now ordered by time posted
  src/ChirpInfrastructure/CheepRepository.cs
Labels: minor fix

#113 Merge this AFTER Ordering of Cheeps: Two ("three") API tests added in Chirp.ChirpWeb.Tests
  src/ChirpWeb/ChirpWeb.csproj
  src/ChirpWeb/Program.cs
  test/Chirp.ChirpWeb.Tests/API_Tests.cs
  test/Chirp.ChirpWeb.Tests/Chirp.ChirpWeb.Tests.csproj
Labels: testing

#122 Refactoring of Repository and Service pattern and methods within
  src/ChirpInfrastructure/AuthorRepository.cs
  src/ChirpInfrastructure/AuthorService.cs
  src/ChirpInfrastructure/CheepRepository.cs
Labels: documentation, restructuring

#127 Debuggin test folders fmain
  Chirp.sln
  src/ChirpWeb/Program.cs
  test/Chirp.ChirpCore.Tests/Chirp.ChirpCore.Tests.sln
  test/Chirp.ChirpCore.Tests/UnitTests.cs
  test/Chirp.ChirpInfrastructure.Tests/Chirp.ChirpInfrastructure.Tests.sln
  test/Chirp.ChirpWeb.Tests/Chirp.ChirpWeb.Tests.sln
  test/Chirp.CrossTests/Chirp.CrossTests.sln
  test/Chirp_test.sln
Labels: bug
